package app_restaurante.modelo;


public enum CategoriaInventario {
    CARNES,
    PESCADOS_MARISCOS,
    VERDURAS_HORTALIZAS,
    FRUTAS,
    LACTEOS_HUEVOS,
    CEREALES_PAN_PASTA,
    LEGUMBRES,
    SALSAS_ESPECIAS,
    BEBIDAS_ALCOHOLICAS,
    BEBIDAS_NO_ALCOHOLICAS,
    CONGELADOS,
    POSTRES_REPOSTERIA,
    LIMPIEZA_HIGIENE,
    MENAJE_UTENSILIOS,
    OTROS;
}